---
title: 'Previous Bulletin Archive'
output: html_document
---
 
 
| | Jan | Feb | Mar | Apr | May | Jun | Jul | Aug | Sep | Oct | Nov | Dec |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 2023 |[<span style="color: red;">FCWC profile</span>](figures/FCWC/20230108_FCWC.png)|---|---|---|---|---|---|---|---|---|---|---|
| 2022 |[<span style="color: red;">FCWC profile</span>](figures/FCWC/20220106_FCWC_annotated.pdf) [<span style="color: DodgerBlue;">AOML bottom</span>](figures/AOML/WS22022_bottom.png) [<span style="color: DodgerBlue;">AOML surface</span>](figures/AOML/WS22022_underway.png)|---|---|---|[<span style="color: DodgerBlue;">AOML bottom</span>](figures/AOML/WS22141_bottom2.png) [<span style="color: DodgerBlue;">AOML surface</span>](figures/AOML/WS22141_underway.png) |---|---|---|[<span style="color: Black;">NMFS bottom</span>](figures/NOAA/20220913_noaa_plot.png) [<span style="color: Black;">NMFS bottom</span>](figures/NOAA/20220924_noaa_plot.png)|[<span style="color: DodgerBlue;">AOML bottom</span>](figures/AOML/WS22281_bottom.png)|---|[<span style="color: DodgerBlue;">AOML bottom</span>](figures/AOML/WS22337_bottom.png)|
| 2021 |---|---|---|---|---|---|[<span style="color: red;">FCWC profile</span>](figures/FCWC/20210719_FCWC_sampling.pdf)|---|[<span style="color: Black;">NMFS bottom</span>](figures/NOAA/20210908_noaa_plot.png) [<span style="color: Black;">NMFS bottom</span>](figures/NOAA/20210920_noaa_plot.png)|[<span style="color: red;">FCWC profile</span>](figures/FCWC/20211016_FCWC_annotated.pdf)|[<span style="color: Black;">NMFS bottom</span>](figures/NOAA/20211124_noaa_plot.png)|---|
| 2020 |---|---|---|---|[<span style="color: red;">FCWC profile</span>](figures/FCWC/20200506_FCWC_profile.pdf)|---|---|[<span style="color: red;">FCWC profile</span>](figures/FCWC/20200816_FCWC_update.pdf)|---|---|---|---|

-----

#### AOML

Data collected by the [R/V Walton Smith](https://www.earth.miami.edu/about-us/administration/marine-operations/f-g-walton-smith-vessel/index.html) unless noted otherwise.

-----

#### FCWC

Florida Commercial Watermen's Conservation ([FCWC](https://floridawatermen.org))

-----

#### NMFS

Data collected by [NOAA research vessels](https://www.omao.noaa.gov/find/fleet/ships).

